version: '3.8'
services:

  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    env_file:
      - ./backend/.env
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 4000:4000
      - 5555:5555
    volumes:
      - ./backend:/usr/src/app
      - back_node_modules:/usr/src/app/node_modules
    networks:
      - my_network
    env_file:
      - ./backend/.env
    depends_on:
      - database
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - front_node_modules:/usr/src/app/node_modules
    networks:
      - my_network
    depends_on:
      - backend
    restart: always


volumes:
  postgres_data:
  front_node_modules:
  back_node_modules:

networks:
  my_network:
    name: transcendence
    driver: bridge
